// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDf08UDo1KTg2E0NHLyIjMnRDHD_x-AOU',
    appId: '1:364475003910:web:d76fe9fd16cbbeff9dbf87',
    messagingSenderId: '364475003910',
    projectId: 'flutterproject-da6a0',
    authDomain: 'flutterproject-da6a0.firebaseapp.com',
    storageBucket: 'flutterproject-da6a0.appspot.com',
    measurementId: 'G-8LLYNY2QN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVYaMyO_u_etlwmBHVyg15dsbuCoItric',
    appId: '1:364475003910:android:18baaceaa9fb5b679dbf87',
    messagingSenderId: '364475003910',
    projectId: 'flutterproject-da6a0',
    storageBucket: 'flutterproject-da6a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGvaFYyVDW2ZVK3perp6kjsA3x9kTzWR0',
    appId: '1:364475003910:ios:6d0d4a7a61c689c69dbf87',
    messagingSenderId: '364475003910',
    projectId: 'flutterproject-da6a0',
    storageBucket: 'flutterproject-da6a0.appspot.com',
    iosBundleId: 'com.example.nepaltradingysytem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGvaFYyVDW2ZVK3perp6kjsA3x9kTzWR0',
    appId: '1:364475003910:ios:515cce7a412058f39dbf87',
    messagingSenderId: '364475003910',
    projectId: 'flutterproject-da6a0',
    storageBucket: 'flutterproject-da6a0.appspot.com',
    iosBundleId: 'com.example.nepaltradingysytem.RunnerTests',
  );
}
